// CSV download (opens cleanly in Excel: UTF-8 BOM, quoted fields).

import { TENANT } from "@/config/tenant";

/** `footer` replaces the default data-mode line (journal proposals carry their own wording). */
export function downloadCsv(filename: string, header: string[], rows: (string | number)[][], footer?: string): void {
  const esc = (v: string | number) => {
    const s = String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const foot = footer ?? (TENANT.dataMode === "demo" ? "Generated by LedgerAlpha on demo data" : "");
  const csv = [header, ...rows, ...(foot ? [[foot]] : [])].map((r) => r.map(esc).join(",")).join("\r\n");
  const blob = new Blob(["﻿" + csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
