// CSV download (opens cleanly in Excel: UTF-8 BOM, quoted fields).

import { TENANT } from "@/config/tenant";

export function downloadCsv(filename: string, header: string[], rows: (string | number)[][]): void {
  const esc = (v: string | number) => {
    const s = String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const footer = TENANT.dataMode === "demo" ? [["Generated by LedgerAlpha on demo data"]] : [];
  const csv = [header, ...rows, ...footer].map((r) => r.map(esc).join(",")).join("\r\n");
  const blob = new Blob(["﻿" + csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
