import { Download } from "lucide-react";
import { Panel, StatusChip } from "@/components/vocab";
import { Fields } from "@/components/vocab/Fields";
import { Button } from "@/components/ui/button";
import { GL_BY_ID, WORLD, statementItems } from "@/data";
import type { RecRow } from "@/state/recHooks";
import { useWorkflow } from "@/state/workflow";
import { useRoleStore } from "@/lib/stores";
import { ROLES, can } from "@/config/roles";
import { downloadCsv } from "@/lib/exportCsv";
import { ageOf } from "@/engine/review";
import { fmtDate, fmtDateTime } from "@/lib/dates";
import { fmtDrCr, fmtINR } from "@/lib/format";
import { toast } from "@/lib/toast";

/** Counterparty confirmation: request, reply, and the statement of account we send. */
export function ConfirmationPanel({ row }: { row: RecRow }) {
  const role = useRoleStore((s) => s.role);
  const { markConfirmationSent, applyReply } = useWorkflow.getState();
  const { rec, view } = row;
  const conf = view.confirmation;
  if (!conf) return null;

  const locked = !!row.signOff?.preparer;
  const replyPending = !!rec.reply && !view.work?.source;
  const reply = replyPending ? rec.reply : undefined;

  const download = () => {
    const items = statementItems(rec);
    downloadCsv(
      `statement-${rec.id}.csv`,
      ["Document", "Posting date", "Due date", "Reference", "Account", "Text", "Amount (INR)", "Dr / Cr", "Age (days)"],
      items.map((l) => [l.docNo, fmtDate(l.postingDate), l.dueDate ? fmtDate(l.dueDate) : "", l.assignment ?? l.reference ?? "", GL_BY_ID.get(l.gl)?.description ?? l.gl, l.text ?? "", Math.abs(l.amount).toFixed(2), l.amount < 0 ? "Cr" : "Dr", ageOf(l, WORLD.asOf)]),
      `Statement of account for ${rec.name} at ${fmtDate(WORLD.asOf)}. Balance per our books ${fmtDrCr(rec.booksBalance)}. Please confirm the balance or send your statement. Generated by LedgerAlpha on demo data.`
    );
    toast("Statement downloaded", { description: `${items.length} open items`, tone: "ok" });
  };

  const rows: [string, React.ReactNode][] = [
    ["Status", <StatusChip key="s" status={conf.status} />],
    ["Contact", conf.contact],
    ["Requested", conf.sentAt ? fmtDateTime(conf.sentAt) : "Not yet sent"],
  ];
  if (conf.repliedAt) rows.push(["Reply received", fmtDateTime(conf.repliedAt)]);
  if (reply) {
    rows.push(["Balance per reply", fmtDrCr(reply.balance)]);
    rows.push(["Difference", fmtDrCr(rec.booksBalance - reply.balance)]);
    rows.push(["Received through", reply.via]);
  }

  return (
    <Panel title="Confirmation">
      <div className="-mx-4 -mt-4">
        <Fields rows={rows} compact />
      </div>
      <div className="mt-3 flex flex-wrap gap-2">
        {conf.status === "not-sent" && (
          <Button
            size="sm"
            disabled={!can(role, "follow-up") || locked}
            title={can(role, "follow-up") ? "Records the request; nothing is sent from the prototype" : `${ROLES[role].label} cannot request confirmations`}
            onClick={() => {
              const r = markConfirmationSent(rec.id);
              if (r.ok) toast("Confirmation request recorded", { tone: "ok" });
              else toast(r.error, { tone: "danger" });
            }}
          >
            Send confirmation request
          </Button>
        )}
        {replyPending && (
          <Button
            size="sm"
            disabled={!can(role, "propose") || locked}
            title={can(role, "propose") ? "The reconciler explains the difference from the ledger" : `${ROLES[role].label} cannot apply replies`}
            onClick={() => {
              const r = applyReply(rec.id);
              if (!r.ok) return toast(r.error, { tone: "danger" });
              if (r.found > 0) toast(`${r.found} item${r.found === 1 ? "" : "s"} explain the difference exactly`, { description: "Review the classes, then propose entries or follow-ups", tone: "ok" });
              else if (rec.type === "Customer statement") toast("No combination of ledger items explains the difference", { description: `Add the reconciling items by hand; ${fmtINR(Math.abs(rec.booksBalance - rec.reply!.balance))} is unexplained`, tone: "warn" });
              else toast("Reply applied", { tone: "ok" });
            }}
          >
            Apply reply and diagnose
          </Button>
        )}
        <Button size="sm" variant="outline" className="gap-1.5" onClick={download}>
          <Download className="h-3.5 w-3.5" /> Statement of account
        </Button>
      </div>
    </Panel>
  );
}
