import { useMemo } from "react";
import { Download } from "lucide-react";
import { Panel, StatusChip } from "@/components/vocab";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { DecisionQueue, type QueueEntry } from "@/components/review/DecisionQueue";
import { WORLD } from "@/data";
import { useProposalDecisions } from "@/state/journalHooks";
import { useItemDrawer } from "@/state/drawer";
import { EXPORT_COLUMNS, buildProposal, exportRows } from "@/engine/journals";
import { MODULES } from "@/lib/modules";
import { downloadCsv } from "@/lib/exportCsv";
import { fmtDate, fmtDateTime } from "@/lib/dates";
import { fmtINR, fmtInt } from "@/lib/format";

const moduleLabel = (id: string) => MODULES.find((m) => m.id === id)?.label ?? id;

/** The outbox: journal proposals from every module, approved and exported from one place. */
export function ProposedTab() {
  const decisions = useProposalDecisions();
  const open = useItemDrawer((s) => s.open);

  const entries = useMemo(() => {
    const out: QueueEntry[] = [];
    for (const d of decisions) {
      const p = buildProposal(d)!;
      const lines = p.kind === "CLEARING" ? "Clearing instruction" : p.lines.map((l) => `${l.side} ${l.gl || "target to be confirmed"}`).join(" · ");
      out.push({ decision: d, source: moduleLabel(d.module), primary: p.header, secondary: lines, open: () => open(d.itemKey) });
    }
    return out;
  }, [decisions, open]);

  const batches = useMemo(() => {
    const m = new Map<string, typeof decisions>();
    for (const d of decisions) {
      if (!d.exportBatchId) continue;
      m.set(d.exportBatchId, [...(m.get(d.exportBatchId) ?? []), d]);
    }
    return [...m.entries()].sort((a, b) => b[0].localeCompare(a[0]));
  }, [decisions]);

  const download = (batchId: string, ds: typeof decisions) => {
    const out = exportRows(ds, batchId, WORLD.asOf).map((r) => [r.proposalId, r.companyCode, fmtDate(r.postingDate), r.docType, r.header, r.lineNo, r.gl, r.account, r.side, r.amount, r.profitCentre, r.wbs, r.text, r.source, r.approvals]);
    downloadCsv(`journal-proposals-${batchId}.csv`, EXPORT_COLUMNS, out, "Proposal only - to be reviewed and posted by the company in the ERP. Generated by LedgerAlpha on demo data.");
  };

  return (
    <div className="space-y-4">
      <DecisionQueue title="Journal proposals from all modules" sourceLabel="From" itemLabel="Entry" entries={entries} />
      <Panel title="Export batches" bodyClassName="p-0">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Batch</TableHead>
              <TableHead className="text-right">Entries</TableHead>
              <TableHead className="text-right">Value</TableHead>
              <TableHead>Last approved</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="w-28" />
            </TableRow>
          </TableHeader>
          <TableBody>
            {batches.map(([id, ds]) => {
              const posted = ds.every((d) => d.status === "closed-in-erp");
              return (
                <TableRow key={id}>
                  <TableCell className="py-2 font-mono text-xs">{id}</TableCell>
                  <TableCell className="py-2 text-right tnum">{fmtInt(ds.length)}</TableCell>
                  <TableCell className="py-2 text-right tnum">{fmtINR(ds.reduce((s, d) => s + Math.abs(d.amount), 0))}</TableCell>
                  <TableCell className="py-2 text-xs text-muted-foreground">{fmtDateTime(ds[0].approvals[ds[0].approvals.length - 1]?.at ?? ds[0].proposedAt)}</TableCell>
                  <TableCell className="py-2">
                    <StatusChip status={posted ? "closed-in-erp" : "exported"} />
                  </TableCell>
                  <TableCell className="py-2 text-right">
                    <Button size="sm" variant="ghost" className="h-7 gap-1.5" onClick={() => download(id, ds)}>
                      <Download className="h-3.5 w-3.5" /> File
                    </Button>
                  </TableCell>
                </TableRow>
              );
            })}
            {batches.length === 0 && (
              <TableRow>
                <TableCell colSpan={6} className="py-10 text-center text-sm text-muted-foreground">
                  No proposals exported yet
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </Panel>
    </div>
  );
}
