import { useMemo, useState } from "react";
import { Check, Download } from "lucide-react";
import { Panel, StatusChip } from "@/components/vocab";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { useSchedules } from "@/state/auditHooks";
import { useWorkflow } from "@/state/workflow";
import { useQueryParams } from "@/lib/useQueryParams";
import { scheduleRows, scheduleWorkbook, type AccountSchedule } from "@/engine/schedule";
import type { Cell } from "@/lib/xlsx";
import { downloadXlsx } from "@/lib/xlsx";
import { fmtDrCr, fmtInt } from "@/lib/format";
import { toast } from "@/lib/toast";

const READINESS = [
  { key: "ready", label: "Signed off" },
  { key: "in-progress", label: "In progress" },
  { key: "not-started", label: "Not started" },
];

const MONEY = new Intl.NumberFormat("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const render = (c: Cell): { text: string; bold: boolean; num: boolean } => {
  if (c === null || c === undefined) return { text: "", bold: false, num: false };
  if (typeof c === "object") return { text: typeof c.v === "number" ? (c.format === "int" ? new Intl.NumberFormat("en-IN").format(c.v) : MONEY.format(c.v)) : String(c.v), bold: !!c.bold, num: typeof c.v === "number" };
  return { text: String(c), bold: false, num: typeof c === "number" };
};

const noteFor = (list: AccountSchedule[]) =>
  `Generated by LedgerAlpha on demo data.${list.some((s) => s.readiness !== "ready") ? " Schedules not signed off by the reviewer are drafts." : ""}`;

function Preview({ s, onClose }: { s?: AccountSchedule; onClose: () => void }) {
  const rows = useMemo(() => (s ? scheduleRows(s) : []), [s]);
  return (
    <Dialog open={!!s} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="max-w-5xl">
        {s && (
          <>
            <DialogHeader>
              <DialogTitle>
                {s.gl} · {s.description}
              </DialogTitle>
              <DialogDescription>The sheet as it appears in the workbook</DialogDescription>
            </DialogHeader>
            <div className="max-h-[60vh] overflow-auto rounded-md border border-border">
              <table className="w-full text-xs">
                <tbody>
                  {rows.slice(0, 90).map((r, i) => (
                    <tr key={i} className="border-b border-border/50 last:border-0">
                      {r.length === 0 ? (
                        <td className="h-3" />
                      ) : (
                        r.map((c, j) => {
                          const x = render(c);
                          return (
                            <td key={j} className={`max-w-56 truncate px-2 py-1 ${x.bold ? "font-semibold" : ""} ${x.num ? "text-right tnum" : ""}`} title={x.text}>
                              {x.text}
                            </td>
                          );
                        })
                      )}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {rows.length > 90 && <div className="text-xs text-muted-foreground">Showing the first 90 of {fmtInt(rows.length)} rows; the workbook has them all.</div>}
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}

export function SchedulesTab() {
  const schedules = useSchedules();
  const recordExport = useWorkflow((w) => w.recordExport);
  const [params, setParams] = useQueryParams();
  const [chosen, setChosen] = useState<Set<string>>(new Set());
  const ready = params.get("sready") ?? "all";
  const category = params.get("scat") ?? "all";
  const q = params.get("sq") ?? "";
  const previewGl = params.get("sched");

  const categories = useMemo(() => [...new Set(schedules.map((s) => s.category))].sort(), [schedules]);
  const shown = useMemo(
    () =>
      schedules.filter(
        (s) =>
          (ready === "all" || s.readiness === ready) &&
          (category === "all" || s.category === category) &&
          (!q || s.description.toLowerCase().includes(q.toLowerCase()) || s.gl.includes(q))
      ),
    [schedules, ready, category, q]
  );
  const targets = shown.filter((s) => chosen.has(s.gl));
  const exportList = targets.length ? targets : shown;

  const doExport = () => {
    if (!exportList.length) return;
    downloadXlsx(`auditor-schedules-${exportList[0].period}.xlsx`, scheduleWorkbook(exportList, noteFor(exportList)));
    recordExport("Auditor schedules", { accounts: exportList.length, signedOff: exportList.filter((s) => s.readiness === "ready").length });
    toast(`${exportList.length} schedule${exportList.length === 1 ? "" : "s"} exported`, { description: "One workbook, a summary sheet and a sheet per account", tone: "ok" });
  };

  return (
    <>
      <Panel title="Account schedules" bodyClassName="p-0">
        <div className="flex flex-wrap items-center gap-2 border-b border-border/70 px-4 py-2.5">
          <Select value={ready} onValueChange={(v) => setParams({ sready: v === "all" ? null : v })}>
            <SelectTrigger className="h-8 w-44">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All statuses</SelectItem>
              {READINESS.map((r) => (
                <SelectItem key={r.key} value={r.key}>
                  {r.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={category} onValueChange={(v) => setParams({ scat: v === "all" ? null : v })}>
            <SelectTrigger className="h-8 w-52">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All categories</SelectItem>
              {categories.map((c) => (
                <SelectItem key={c} value={c}>
                  {c}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Input value={q} onChange={(e) => setParams({ sq: e.target.value || null })} placeholder="Name or account" className="h-8 w-44" />
          <span className="text-xs text-muted-foreground">{fmtInt(shown.length)} schedules</span>
          <div className="flex-1" />
          <Button size="sm" variant="outline" className="h-8 gap-1.5" disabled={!exportList.length} onClick={doExport}>
            <Download className="h-3.5 w-3.5" /> Export workbook{targets.length ? ` (${targets.length})` : ""}
          </Button>
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="w-8 pr-0">
                <input type="checkbox" aria-label="Select all schedules shown" checked={shown.length > 0 && shown.every((s) => chosen.has(s.gl))} onChange={(e) => setChosen(e.target.checked ? new Set(shown.map((s) => s.gl)) : new Set())} />
              </TableHead>
              <TableHead>Account</TableHead>
              <TableHead>Statement line</TableHead>
              <TableHead className="text-right">Closing</TableHead>
              <TableHead className="text-center">Trial balance</TableHead>
              <TableHead className="text-right">Items listed</TableHead>
              <TableHead className="text-right">Decisions</TableHead>
              <TableHead className="text-right">Reconciliations</TableHead>
              <TableHead>Status</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {shown.map((s) => (
              <TableRow key={s.gl} className="cursor-pointer" onClick={() => setParams({ sched: s.gl })}>
                <TableCell className="w-8 pr-0" onClick={(e) => e.stopPropagation()}>
                  <input
                    type="checkbox"
                    aria-label={`Select ${s.description}`}
                    checked={chosen.has(s.gl)}
                    onChange={() =>
                      setChosen((c) => {
                        const n = new Set(c);
                        if (n.has(s.gl)) n.delete(s.gl);
                        else n.add(s.gl);
                        return n;
                      })
                    }
                  />
                </TableCell>
                <TableCell className="max-w-64 py-2">
                  <div className="truncate text-sm">{s.description}</div>
                  <div className="font-mono text-2xs text-muted-foreground">{s.gl}</div>
                </TableCell>
                <TableCell className="max-w-56 truncate py-2 text-xs">{s.statementLine}</TableCell>
                <TableCell className="whitespace-nowrap py-2 text-right tnum text-sm">{fmtDrCr(s.rollForward.closing, true)}</TableCell>
                <TableCell className="py-2 text-center">{s.rollForward.ties ? <Check className="mx-auto h-4 w-4 text-ok" aria-label="Agrees to the trial balance" /> : <span className="text-xs text-danger-foreground">Differs</span>}</TableCell>
                <TableCell className="py-2 text-right tnum text-sm">{s.items.length ? fmtInt(s.items.length) : "-"}</TableCell>
                <TableCell className="py-2 text-right tnum text-sm">{s.decisions.length ? fmtInt(s.decisions.length) : "-"}</TableCell>
                <TableCell className="py-2 text-right tnum text-sm">{s.recs.length ? fmtInt(s.recs.length) : "-"}</TableCell>
                <TableCell className="py-2">
                  {s.blockers.length ? (
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <span>
                          <StatusChip status={s.status} />
                        </span>
                      </TooltipTrigger>
                      <TooltipContent>
                        <ul className="space-y-0.5">
                          {s.blockers.map((b) => (
                            <li key={b}>{b}</li>
                          ))}
                        </ul>
                      </TooltipContent>
                    </Tooltip>
                  ) : (
                    <StatusChip status={s.status} />
                  )}
                </TableCell>
              </TableRow>
            ))}
            {shown.length === 0 && (
              <TableRow>
                <TableCell colSpan={9} className="py-10 text-center text-sm text-muted-foreground">
                  No schedules match
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </Panel>
      <Preview s={schedules.find((s) => s.gl === previewGl)} onClose={() => setParams({ sched: null })} />
    </>
  );
}
